bibtex_examples = {
    "article": {
        "author": "Doe, John and Smith, Jane",
        "title": "An Example Article",
        "journal": "Journal of Examples",
        "year": "2020",
        "volume": "42",
        "number": "3",
        "pages": "123-145",
        "month": "jan",
        "note": "An optional note",
        "entry-type": "article"
    },
    "book": {
        "author": "Doe, John",
        "title": "The Example Book",
        "publisher": "Fictional Press",
        "year": "2019",
        "volume": "1",
        "series": "Examples Series",
        "address": "New York",
        "edition": "2nd",
        "month": "feb",
        "note": "Optional note",
        "entry-type": "book"
    },
    "inbook": {
        "author": "Smith, Jane",
        "title": "Chapter Example",
        "chapter": "3",
        "pages": "45-67",
        "publisher": "Academic Press",
        "year": "2016",
        "volume": "2",
        "series": "Book Series",
        "type": "Chapter",
        "address": "London",
        "edition": "1st",
        "month": "may",
        "note": "Optional note",
        "entry-type": "inbook"
    },
    "booklet": {
        "title": "The Example Booklet",
        "author": "Jane Smith",
        "howpublished": "Available online",
        "address": "Los Angeles",
        "year": "2018",
        "month": "mar",
        "note": "Optional note",
        "entry-type": "booklet"
    },
    "conference": {
        "author": "Doe, John",
        "title": "Conference Example",
        "booktitle": "Proceedings of the Example Conference",
        "year": "2017",
        "editor": "Brown, Alice",
        "volume": "10",
        "series": "Conference Series",
        "pages": "50-60",
        "address": "Paris",
        "month": "apr",
        "publisher": "Conference Press",
        "note": "Optional note",
        "entry-type": "conference"
    },
    "proceedings": {
        "title": "Proceedings of ExampleConf",
        "year": "2009",
        "editor": "Johnson, Mike",
        "volume": "8",
        "series": "Proceedings Series",
        "address": "Madrid",
        "month": "dec",
        "publisher": "Proceedings Press",
        "note": "Optional note",
        "entry-type": "proceedings"
    },
    "inproceedings": {
        "author": "Smith, Jane",
        "title": "An Example Paper",
        "booktitle": "Proceedings of ExampleConf",
        "year": "2014",
        "editor": "Miller, Kate",
        "volume": "12",
        "series": "Proceedings Series",
        "pages": "101-110",
        "address": "Tokyo",
        "month": "jul",
        "publisher": "Tech Press",
        "note": "Optional note",
        "entry-type": "inproceedings"
    },
    "incollection": {
        "author": "Doe, John",
        "title": "A Section in a Collection",
        "booktitle": "Collected Works on Examples",
        "publisher": "Collection Press",
        "year": "2015",
        "editor": "Taylor, Bob",
        "volume": "5",
        "series": "Collections",
        "type": "Section",
        "chapter": "4",
        "pages": "78-92",
        "address": "Berlin",
        "edition": "1st",
        "month": "jun",
        "note": "Optional note",
        "entry-type": "incollection"
    },
    "phdthesis": {
        "author": "Smith, Jane",
        "title": "PhD Thesis Example",
        "school": "Fictional Institute of Technology",
        "year": "2010",
        "type": "PhD Thesis",
        "address": "San Francisco",
        "month": "nov",
        "note": "Optional note",
        "entry-type": "phdthesis"
    },
    "mastersthesis": {
        "author": "Smith, Jane",
        "title": "An Example Master's Thesis",
        "school": "Example University",
        "year": "2012",
        "type": "Master's Thesis",
        "address": "Boston",
        "month": "sep",
        "note": "Optional note",
        "entry-type": "mastersthesis"
    },
    "manual": {
        "title": "Example Manual",
        "author": "Doe, John",
        "organization": "Example Org",
        "address": "Chicago",
        "edition": "3rd",
        "year": "2013",
        "month": "aug",
        "note": "Optional note",
        "entry-type": "manual"
    },
    "misc": {
        "author": "Doe, John",
        "title": "Miscellaneous Example",
        "howpublished": "Personal communication",
        "year": "2011",
        "month": "oct",
        "note": "Optional note",
        "entry-type": "misc"
    },
    "techreport": {
        "author": "Doe, John",
        "title": "An Example Technical Report",
        "institution": "Example Institute",
        "year": "2008",
        "type": "Technical Report",
        "number": "TR-1234",
        "address": "Zurich",
        "month": "jan",
        "note": "Optional note",
        "entry-type": "techreport"
    },
    "unpublished": {
        "author": "Smith, Jane",
        "title": "Unpublished Example",
        "note": "Manuscript in preparation",
        "year": "2007",
        "month": "feb",
        "entry-type": "unpublished"
    }
}
